name: sgeop
channels:
  - conda-forge
dependencies:
  - python=3.12
  - esda>=2.5.1
  - geopandas>=1.0.0
  - libpysal>=4.12
  - momepy>=0.8.1
  - networkx>=2.8
  - numpy>=1.22
  - pandas>=1.5.1
  - scipy>=1.9
  - shapely>=2.0.4
  # testing
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
