name: sgeop
channels:
  - conda-forge
dependencies:
  - python=3.12
  - esda>=2.5.1
  - geopandas>=0.13.0
  - libpysal
  - momepy>=0.8.1
  - networkx>=2.8
  - numpy
  - pandas>=1.5.1
  - scipy
  - shapely>=2
  # testing
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
