name: sgeop
channels:
  - conda-forge
dependencies:
  - python=3.12
  - esda>=2.5.1
  - geopandas>=1.0.0
  - libpysal>=4.10
  - momepy>=0.8.1
  - networkx>=2.8
  - numpy>=1.22
  - pandas>=1.5.1
  - scipy>=1.8
  - shapely>=2
  # testing
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
