---
name: neatnet
channels:
  - conda-forge
dependencies:
  - python=3.13
  - esda>=2.6.0
  - geopandas>=1.0.1
  - libpysal>=4.12.1
  - momepy>=0.9.0
  - networkx>=3.3
  - numpy>=2
  - pandas>=2.2.3
  - scipy>=1.14.1
  - shapely>=2.0.6
  - scikit-learn>=1.2.0
  # testing
  - codecov
  - coverage
  - matplotlib
  - mypy>=1.15.0,<2
  - pre-commit
  - pyarrow>=17.0
  - pytest
  - pytest-cov
  - pytest-xdist
  - ruff
  - yamllint
  # docs
  - ipykernel
  - ipywidgets
  - jupyterlab
  - myst-nb
  - numpydoc
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-autosummary-accessors
  - sphinx-book-theme
  - sphinx-copybutton
